"""
NLM RPC Registry — Dynamic RPC ID management for NotebookLM proxy.

NotebookLM's batchexecute RPC IDs are generated by Google's closure compiler and
tied to the frontend build label (BL). They are stable within a build but CAN
change when Google deploys a new frontend (~weekly).

This module:
- Stores the known operation → RPC ID mapping
- Provides the proxy with current IDs at runtime
- Detects when IDs have changed (by checking if a known RPC returns 404)
- Triggers re-discovery via ``nlm_automation.py`` when staleness is detected

Storage:
    ``data/nlm_rpc_registry.json`` — persisted mapping, updated by automation

Usage::

    from engine.nexus.nlm_rpc_mapper import get_rpc_id, get_registry, invalidate

    rpc = get_rpc_id("ASK_QUESTION")      # → "s0tc2d" (or current equivalent)
    rpc = get_rpc_id("LOAD_NOTEBOOK")     # → "rLM1Ne"
    rpc = get_rpc_id("CREATE_NOTEBOOK")   # → "CCqFvf" (if captured)

    # Force re-run of automation to refresh all IDs
    invalidate()
"""
from __future__ import annotations

import json
import logging
import time
from datetime import datetime, timedelta
from pathlib import Path
from typing import Any, Dict, List, Optional

logger = logging.getLogger(__name__)

_PROJECT_ROOT = Path(__file__).resolve().parent.parent.parent
_REGISTRY_FILE = _PROJECT_ROOT / "data" / "nlm_rpc_registry.json"

# ── Hardcoded fallback RPC IDs (confirmed from 8 HAR files, build ~20260226) ──
# These are used when the registry file is absent or an operation has no entry.
# Format: OPERATION_NAME → RPC_ID
_FALLBACK_RPC_IDS: Dict[str, str] = {
    # ── Read operations ──
    "LOAD_HOMEPAGE":           "ZwVcOc",   # Session init + account limits
    "LIST_NOTEBOOKS":          "ub2Bae",   # List all user notebooks
    "LOAD_NOTEBOOK":           "rLM1Ne",   # Load notebook by ID (also used as poll)
    "GET_SOURCES":             "wXbhsf",   # Get notebook sources + state
    "GET_NOTEBOOK_INFO":       "e3bVqc",   # Full notebook info blob
    "GET_AI_OVERVIEW":         "VfAZjd",   # AI-generated notebook overview
    "GET_CONVERSATION_THREADS": "hPTbtc",  # Get conversation thread IDs
    "READ_CONVERSATION":       "khqZz",    # Read messages from a thread
    "LIST_ARTIFACTS":          "gArtLc",   # List saved artifacts (notes, guides)
    "GET_USER_PROFILE":        "JFMDGd",   # User profile + queries remaining
    "GET_ACCOUNT_STATE":       "ozz5Z",    # Account UI state + subscription
    "GET_SESSION_LIMITS":      "ZwVcOc",   # Account limits (same as homepage init)
    "LIST_AUDIO_TYPES":        "sqTeoe",   # Audio overview type list
    "READ_SOURCE":             "tr032e",   # Get source AI summary
    "RESUME_SESSION":          "CCqFvf",   # Load last active notebook

    # ── Write operations ──
    "ASK_QUESTION":            "s0tc2d",   # Async chat / Q&A
    "CREATE_NOTE":             "CYK0Xb",   # Save text note to notebook
    "GENERATE_REPORT":         "R7cb6c",   # Generate + save document/report
    "GENERATE_SUGGESTED":      "ciyUvf",   # Generate suggested report preview
    "GENERATE_MIND_MAP":       "cFji9",    # Generate / get mind map

    # ── Fast Research flow ──
    "FAST_RESEARCH_START":     "Ljjv0c",   # Start fast research (web search)
    "ADD_URL_SOURCE":          "LBwxtb",   # Add URL sources (batch)
    "POLL_SOURCES":            "rLM1Ne",   # Poll for source processing completion

    # ── Proto/gRPC (not batchexecute) ──
    "GENERATE_FREE_FORM":      "GenerateFreeFormStreamed",  # Fast research AI report

    # ── Not yet captured (placeholders) ──
    "DELETE_NOTEBOOK":         None,       # Unknown — never captured
    "DELETE_SOURCE":           None,       # Unknown — never captured
    "RENAME_NOTEBOOK":         None,       # Unknown — never captured
    "ADD_TEXT_SOURCE":         None,       # Unknown — never captured
    "ADD_FILE_SOURCE":         None,       # Unknown — separate upload endpoint
    "GENERATE_AUDIO_OVERVIEW": None,       # Unknown — trigger RPC not captured
    "SHARE_NOTEBOOK":          None,       # Unknown — never captured
}

# Inverse map: RPC_ID → operation name (for logging)
_FALLBACK_RPC_TO_OP: Dict[str, str] = {
    v: k for k, v in _FALLBACK_RPC_IDS.items() if v
}

# How long before the registry is considered stale (days)
_REGISTRY_MAX_AGE_DAYS = 10


class NLMRPCRegistry:
    """Thread-safe RPC ID registry with file persistence and fallback."""

    def __init__(self) -> None:
        self._data: Dict[str, Any] = {}
        self._loaded_at: float = 0.0
        self._load()

    def _load(self) -> None:
        if _REGISTRY_FILE.exists():
            try:
                with open(_REGISTRY_FILE, encoding="utf-8") as f:
                    self._data = json.load(f)
                self._loaded_at = time.time()
                logger.debug("Loaded NLM RPC registry from %s", _REGISTRY_FILE)
                return
            except Exception as exc:
                # v1.58.0 [2026-06-11] — Quarantine the corrupt file so the
                # next automation/RpcidUpdater run regenerates it cleanly
                # instead of erroring forever ("Extra data" parse loop).
                logger.warning(
                    "[nlm_rpc_mapper] Corrupt registry quarantined "
                    "(operation=load, file=%s): %s", _REGISTRY_FILE, exc)
                try:
                    import os
                    os.replace(_REGISTRY_FILE,
                               _REGISTRY_FILE.with_suffix(".json.corrupt"))
                except OSError:
                    pass
        self._data = {"rpc_ids": {}, "updated_at": None}
        self._loaded_at = time.time()

    def _reload_if_stale(self) -> None:
        """Reload from disk if file has been updated since last load."""
        if not _REGISTRY_FILE.exists():
            return
        try:
            file_mtime = _REGISTRY_FILE.stat().st_mtime
            if file_mtime > self._loaded_at:
                self._load()
        except Exception:
            pass

    def get_rpc_id(self, operation: str) -> Optional[str]:
        """
        Get the current RPC ID for an operation.

        Checks registry first, falls back to hardcoded defaults.

        Args:
            operation: Operation name (e.g., "ASK_QUESTION", "LOAD_NOTEBOOK").

        Returns:
            RPC ID string or None if unknown.
        """
        self._reload_if_stale()
        rpc_ids = self._data.get("rpc_ids", {})
        if operation in rpc_ids and rpc_ids[operation]:
            return rpc_ids[operation]
        return _FALLBACK_RPC_IDS.get(operation)

    def get_operation(self, rpc_id: str) -> str:
        """Reverse lookup: get operation name for an RPC ID."""
        self._reload_if_stale()
        for op, rid in self._data.get("rpc_ids", {}).items():
            if rid == rpc_id:
                return op
        return _FALLBACK_RPC_TO_OP.get(rpc_id, f"UNKNOWN({rpc_id})")

    def is_stale(self) -> bool:
        """True if the registry hasn't been refreshed recently."""
        updated_at = self._data.get("updated_at")
        if not updated_at:
            return True
        try:
            age = datetime.now() - datetime.fromisoformat(updated_at)
            return age > timedelta(days=_REGISTRY_MAX_AGE_DAYS)
        except Exception:
            return True

    def get_all(self) -> Dict[str, str]:
        """Return the merged registry (file + fallbacks)."""
        self._reload_if_stale()
        merged = dict(_FALLBACK_RPC_IDS)
        merged.update({k: v for k, v in self._data.get("rpc_ids", {}).items() if v})
        return merged

    def get_unknown_operations(self) -> List[str]:
        """Return operations that still have no captured RPC ID."""
        return [op for op, rpc in _FALLBACK_RPC_IDS.items() if rpc is None]

    def get_bl(self) -> Optional[str]:
        self._reload_if_stale()
        return self._data.get("bl")

    def update_from_automation(self, op_rpc_map: Dict[str, List[str]], bl: Optional[str] = None) -> None:
        """
        Merge an operation → RPC map from automation results.

        Args:
            op_rpc_map: {operation: [rpc_id, ...]} from NLMCapture.
            bl: Current build label.
        """
        rpc_ids = self._data.get("rpc_ids", {})
        for op, rpcs in op_rpc_map.items():
            if rpcs:
                rpc_ids[op] = rpcs[0]
        self._data["rpc_ids"] = rpc_ids
        self._data["updated_at"] = datetime.now().isoformat()
        if bl:
            self._data["bl"] = bl
        # v1.58.0 [2026-06-11] — Atomic write (concurrent scene processes read
        # this file; plain writes caused "Extra data" JSON corruption)
        from engine.utils import atomic_write_json
        atomic_write_json(_REGISTRY_FILE, self._data)
        self._loaded_at = _REGISTRY_FILE.stat().st_mtime + 1
        logger.info("RPC registry updated: %d operations", len(rpc_ids))

    def report(self) -> str:
        """Human-readable registry status report."""
        lines = ["NLM RPC Registry Status"]
        lines.append(f"  Updated: {self._data.get('updated_at', 'never')}")
        lines.append(f"  Stale:   {self.is_stale()}")
        lines.append(f"  BL:      {self.get_bl() or 'unknown'}")
        lines.append("")
        all_ops = self.get_all()
        captured = [(op, rid) for op, rid in all_ops.items() if rid]
        missing = [(op, rid) for op, rid in all_ops.items() if not rid]
        lines.append(f"  Captured ({len(captured)}):")
        for op, rid in sorted(captured):
            source = "registry" if op in self._data.get("rpc_ids", {}) else "fallback"
            lines.append(f"    {op:<35} → {rid}  [{source}]")
        if missing:
            lines.append(f"\n  Missing ({len(missing)}) — need HAR capture:")
            for op, _ in sorted(missing):
                lines.append(f"    {op}")
        return "\n".join(lines)


# Singleton instance
_registry: Optional[NLMRPCRegistry] = None


def get_registry() -> NLMRPCRegistry:
    global _registry
    if _registry is None:
        _registry = NLMRPCRegistry()
    return _registry


def get_rpc_id(operation: str) -> Optional[str]:
    """Convenience: get RPC ID for an operation."""
    return get_registry().get_rpc_id(operation)


def invalidate() -> None:
    """Force registry reload on next access."""
    global _registry
    _registry = None


if __name__ == "__main__":
    logging.basicConfig(level=logging.INFO, format="%(message)s")
    reg = get_registry()
    print(reg.report())
    print(f"\nUnknown operations needing capture: {reg.get_unknown_operations()}")
