"""Scene Template Generator — scaffolds new scene directories.

Creates the standard directory structure and boilerplate files for a new
CosySim scene using the FlaskScene base class.

Version: v1.51.0 [2026-03-22]
Author:  CosySim Team

Change Log:
    v1.51.0 [2026-03-22] — Generate FlaskScene subclasses instead of bare BaseScene.
                            Scenes get MCP, Nexus, SocketIO, shared assets automatically.
    v1.47.0 [2026-03-21] — Initial scene template generator
"""
from __future__ import annotations

import logging
from pathlib import Path
from typing import Optional

logger = logging.getLogger(__name__)

PROJECT_ROOT = Path(__file__).resolve().parents[2]
SCENES_DIR = PROJECT_ROOT / "content" / "scenes"

# v1.51.0 [2026-03-22] — FlaskScene-based template (MCP, Nexus, SocketIO automatic)
_SCENE_PY_TEMPLATE = '''\
"""
{display_name} — CosySim Scene
{header_line}
Port {port}, accent {accent}.

Version: v1.51.0 [2026-03-22]
Author:  CosySim Team (generated by Creation Kit)

Usage:
    python launcher.py {name}
"""
from __future__ import annotations

import logging
from flask import render_template
from engine.scenes.flask_scene import FlaskScene
from engine.port_registry import get_port

logger = logging.getLogger(__name__)

SCENE_ID = "{name}"
DEFAULT_PORT = get_port(SCENE_ID, {port})


class {class_name}(FlaskScene):
    """{display_name} scene.

    CONNECTS: FlaskScene (Flask + SocketIO + MCP + Nexus + shared assets)
    CALLED BY: launcher.py, TUI
    EMITS: SocketIO events, REST API
    """

    SCENE_METADATA = {{
        "name": SCENE_ID,
        "display_name": "{display_name}",
        "port": DEFAULT_PORT,
        "type": "scene",
        "accent_color": "{accent}",
        "description": "{description}",
    }}

    def __init__(self, host: str = "0.0.0.0", port: int = DEFAULT_PORT) -> None:
        super().__init__(host=host, port=port)
        self._register_scene_routes()
        self._register_scene_socketio()

    # ── Routes ────────────────────────────────────────────────────────

    def _register_scene_routes(self) -> None:
        @self.app.route("/")
        def index():
            return render_template("{name}.html")

    # ── SocketIO handlers ─────────────────────────────────────────────

    def _register_scene_socketio(self) -> None:
        @self.socketio.on("connect")
        def on_connect():
            logger.debug("{name}: client connected")

        @self.socketio.on("action")
        def on_action(data):
            logger.debug("{name}: action %s", data.get("action", ""))

    # ── Lifecycle hooks ───────────────────────────────────────────────

    def on_before_serve(self) -> None:
        """Scene-specific setup before serving."""
        pass
'''

_HTML_TEMPLATE = '''\
{{% extends "neon_base.html" %}}

{{% block title %}}{display_name}{{% endblock %}}

{{% block scene_accent %}}
<style>
  :root {{
    --cs-scene-accent: {accent};
    --cs-scene-glow: {accent}59;
  }}
</style>
{{% endblock %}}

{{% block content %}}
<div class="{name}-scene" data-scene="{name}">
  <h1>{display_name}</h1>
  <p>Scene is online.</p>
</div>
{{% endblock %}}
'''

_JS_TEMPLATE = '''\
/**
 * {name}.js — {display_name} scene controller
 */
'use strict';

document.addEventListener('DOMContentLoaded', () => {{
  console.log('[{display_name}] Scene loaded');
}});
'''

_CSS_TEMPLATE = '''\
/* {name}.css — {display_name} scene styles */

.{name}-scene {{
  padding: var(--cs-space-xl, 24px);
  color: var(--cs-text-primary, #e5e7eb);
}}
'''


def create_scene(
    name: str,
    display_name: Optional[str] = None,
    port: int = 5590,
    accent: str = "#00e5ff",
    description: str = "",
    template: str = "basic",
) -> Path:
    """Scaffold a new scene directory with boilerplate files.

    Args:
        name: Machine name (snake_case, e.g. ``"my_scene"``).
        display_name: Human-readable name. Defaults to title-cased *name*.
        port: Default port assignment.
        accent: CSS accent colour hex.
        description: Short scene description.
        template: Template variant (currently only ``"basic"``).

    Returns:
        Path to the created scene directory.

    Raises:
        FileExistsError: If the scene directory already exists.
    """
    scene_dir = SCENES_DIR / name
    if scene_dir.exists():
        raise FileExistsError(f"Scene directory already exists: {scene_dir}")

    display_name = display_name or name.replace("_", " ").title()
    class_name = "".join(w.capitalize() for w in name.split("_")) + "Scene"

    header_line = "=" * (len(display_name) + len(" — CosySim Scene"))
    ctx = {
        "name": name,
        "display_name": display_name,
        "class_name": class_name,
        "port": port,
        "accent": accent,
        "description": description or f"{display_name} scene",
        "header_line": header_line,
    }

    # Create directory structure
    (scene_dir / "templates").mkdir(parents=True, exist_ok=True)
    (scene_dir / "static").mkdir(parents=True, exist_ok=True)

    # Write files
    (scene_dir / "__init__.py").write_text("", encoding="utf-8")
    (scene_dir / f"{name}_scene.py").write_text(
        _SCENE_PY_TEMPLATE.format(**ctx), encoding="utf-8"
    )
    (scene_dir / "templates" / f"{name}.html").write_text(
        _HTML_TEMPLATE.format(**ctx), encoding="utf-8"
    )
    (scene_dir / "static" / f"{name}.js").write_text(
        _JS_TEMPLATE.format(**ctx), encoding="utf-8"
    )
    (scene_dir / "static" / f"{name}.css").write_text(
        _CSS_TEMPLATE.format(**ctx), encoding="utf-8"
    )

    logger.info("Scaffolded scene '%s' at %s", name, scene_dir)
    return scene_dir
