"""
Scene Template Generator
========================

Scaffolds new scene directories with production-quality boilerplate files
following all CLAUDE.md conventions: version headers, section dividers,
navigational comments, test skeletons, and auto-registration.

Version: v1.52.0 [2026-03-22]
Author:  CosySim Team

Change Log:
    v1.52.0 [2026-03-22] — Full rewrite: rich scaffolding with HUD integration,
                            SocketIO patterns, skills skeleton, test file,
                            auto-registration in control_plane_registry + launcher.yaml
    v1.51.0 [2026-03-22] — Generate FlaskScene subclasses instead of bare BaseScene.
                            Scenes get MCP, Nexus, SocketIO, shared assets automatically.
    v1.47.0 [2026-03-21] — Initial scene template generator
"""
from __future__ import annotations

import logging
from datetime import date
from pathlib import Path
from typing import Optional

logger = logging.getLogger(__name__)

PROJECT_ROOT = Path(__file__).resolve().parents[2]
SCENES_DIR = PROJECT_ROOT / "content" / "scenes"


# ──── Python Scene Template ──────────────────────────────────────────────

# v1.52.0 [2026-03-22] — Production-quality FlaskScene subclass
_SCENE_PY_TEMPLATE = '''\
"""
{display_name} — CosySim Scene
{header_line}

{description}

Version: v1.0.0 [{today}]
Author:  CosySim Team (generated by Creation Kit)

Change Log:
    v1.0.0 [{today}] — Initial scaffold via Creation Kit

Usage:
    python launcher.py {name}
    python launcher_game.py {name}
"""
from __future__ import annotations

import logging
from typing import Any, Dict

from flask import jsonify, render_template, request
from flask_socketio import emit

from engine.scenes.flask_scene import FlaskScene
from engine.port_registry import get_port
from engine.world.player_state import get_player_state

logger = logging.getLogger(__name__)

SCENE_ID = "{name}"
DEFAULT_PORT = get_port(SCENE_ID, {port})


# ──── Scene Class ────────────────────────────────────────────────────────


class {class_name}(FlaskScene):
    """{display_name} scene.

    CONNECTS: FlaskScene (Flask + SocketIO + MCP + Nexus + shared assets)
    CALLED BY: launcher.py, launcher_game.py, TUI
    EMITS: SocketIO events (scene_state, hud_update), REST API
    """

    SCENE_METADATA = {{
        "name": SCENE_ID,
        "display_name": "{display_name}",
        "port": DEFAULT_PORT,
        "type": "scene",
        "accent_color": "{accent}",
        "accent_rgb": "{accent_rgb}",
        "description": "{description}",
    }}

    def __init__(self, host: str = "0.0.0.0", port: int = DEFAULT_PORT) -> None:
        super().__init__(host=host, port=port)
        self._setup_routes()
        self._setup_socketio()

    # ── Routes ────────────────────────────────────────────────────────

    def _setup_routes(self) -> None:
        """Register HTTP routes for {display_name}."""

        @self.app.route("/")
        def index():
            return render_template("{name}.html")

        @self.app.route("/api/scene/state")
        def scene_state():
            """Return current scene state snapshot."""
            return jsonify(self._build_state())

    # ── SocketIO Handlers ─────────────────────────────────────────────

    def _setup_socketio(self) -> None:
        """Register Socket.IO event handlers."""

        @self.socketio.on("connect")
        def on_connect():
            logger.info("%s: client connected", SCENE_ID)
            emit("scene_state", self._build_state())

        @self.socketio.on("get_state")
        def on_get_state():
            """Client requests full state refresh."""
            emit("scene_state", self._build_state())

        @self.socketio.on("action")
        def on_action(data: Dict[str, Any]):
            """Handle a client action.

            Args:
                data: Dict with ``action`` (str) and optional payload keys.
            """
            action = (data or {{}}).get("action", "")
            logger.debug("%s: action '%s' payload=%s", SCENE_ID, action, data)
            # TODO: Implement action handlers here

    # ── State Builder ─────────────────────────────────────────────────

    def _build_state(self) -> Dict[str, Any]:
        """Build a scene state snapshot for the client.

        Returns:
            Dict with scene metadata and player state.
        """
        ps = get_player_state()
        return {{
            "scene_id": SCENE_ID,
            "display_name": "{display_name}",
            "player": {{
                "credits": ps.credits,
                "health": ps.health,
                "energy": ps.energy,
                "reputation": ps.reputation,
            }},
        }}

    # ── Lifecycle Hooks ───────────────────────────────────────────────

    def on_before_serve(self) -> None:
        """Scene-specific setup before serving."""
        logger.info("%s scene ready on port %d", "{display_name}", DEFAULT_PORT)
'''


# ──── HTML Template ──────────────────────────────────────────────────────

_HTML_TEMPLATE = '''\
{{%- extends "neon_base.html" -%}}
{{%- set scene_key = "{name}" -%}}
{{%- set scene_display_name = "{display_name}" -%}}
{{%- set scene_accent = "{accent}" -%}}
{{%- set scene_accent_rgb = "{accent_rgb}" -%}}

{{#
  {display_name} — v1.0.0 [{today}]
  Generated by CosySim Creation Kit.
#}}

{{% block head_css %}}
  <link rel="stylesheet" href="{{{{ url_for('static', filename='{name}.css') }}}}">
{{% endblock %}}

{{% block scene_content %}}
<div class="{name}-scene" data-scene="{name}">

  <!-- ── Header ──────────────────────────────────────────────────── -->
  <header class="{name}-header">
    <h1 class="{name}-title">{display_name}</h1>
  </header>

  <!-- ── Main Content ────────────────────────────────────────────── -->
  <main class="{name}-main">
    <section class="cs-glass-panel">
      <h2>Welcome</h2>
      <p>Scene is online. Customize this template in the Creation Kit.</p>
    </section>
  </main>

</div>
{{% endblock %}}

{{% block body_scripts %}}
  <script src="{{{{ url_for('static', filename='{name}.js') }}}}" defer></script>
{{% endblock %}}
'''


# ──── JavaScript Template ────────────────────────────────────────────────

_JS_TEMPLATE = '''\
/**
 * {name}.js — {display_name} Scene Controller
 * {js_header_line}
 *
 * Version: v1.0.0 [{today}]
 * Author:  CosySim Team (generated by Creation Kit)
 *
 * Change Log:
 *   v1.0.0 [{today}] — Initial scaffold via Creation Kit
 */

'use strict';

// ──── Scene App Class ─────────────────────────────────────────────────

class {app_var} {{
  constructor() {{
    this.socket = null;
    this.state = null;
  }}

  // ── Lifecycle ─────────────────────────────────────────────────────

  init() {{
    this._setupSocket();
    console.log('[{display_name}] Scene initialized');
  }}

  // ── Socket.IO ─────────────────────────────────────────────────────

  _setupSocket() {{
    this.socket = io('', {{ transports: ['websocket', 'polling'] }});

    this.socket.on('connect', () => {{
      console.log('[{display_name}] Socket connected');
    }});

    this.socket.on('scene_state', (data) => {{
      this.state = data;
      this._render(data);
    }});

    this.socket.on('hud_update', (data) => {{
      // Handle incremental HUD updates
      if (this.state) Object.assign(this.state, data);
    }});

    this.socket.on('error', (data) => {{
      console.warn('[{display_name}] Error:', data.message || data);
    }});
  }}

  // ── Actions ───────────────────────────────────────────────────────

  /**
   * Send an action to the server.
   * @param {{string}} action - Action type identifier.
   * @param {{Object}} [payload={{}}] - Additional data for the action.
   */
  action(action, payload = {{}}) {{
    if (this.socket) {{
      this.socket.emit('action', {{ action, ...payload }});
    }}
  }}

  /** Request a full state refresh from the server. */
  refresh() {{
    if (this.socket) this.socket.emit('get_state');
  }}

  // ── Rendering ─────────────────────────────────────────────────────

  /**
   * Render scene state to the DOM.
   * @param {{Object}} data - Scene state from server.
   */
  _render(data) {{
    // TODO: Update DOM elements with state data
    console.log('[{display_name}] State received:', data);
  }}
}}

// ──── Bootstrap ─────────────────────────────────────────────────────────

const {app_var} = new {app_var}();

document.addEventListener('DOMContentLoaded', () => {{
  {app_var}.init();
}});
'''


# ──── CSS Template ───────────────────────────────────────────────────────

_CSS_TEMPLATE = '''\
/*
 * {name}.css — {display_name} Scene Styles
 * {css_header_line}
 *
 * Version: v1.0.0 [{today}]
 * Author:  CosySim Team (generated by Creation Kit)
 *
 * Change Log:
 *   v1.0.0 [{today}] — Initial scaffold via Creation Kit
 */

/* ── Palette ────────────────────────────────────────────────────────── */
:root {{
  --{name}-accent: {accent};
  --{name}-accent-rgb: {accent_rgb};
  --{name}-glow: rgba({accent_rgb_csv}, 0.25);
  --{name}-bg: #080a10;
  --{name}-panel: rgba(10, 14, 22, 0.85);
  --{name}-border: rgba({accent_rgb_csv}, 0.12);
  --{name}-text: #c0c8d8;
}}

/* ── Layout ─────────────────────────────────────────────────────────── */
.{name}-scene {{
  padding: var(--cs-space-xl, 24px);
  color: var(--{name}-text);
  min-height: calc(100vh - 60px);
}}

.{name}-header {{
  margin-bottom: 16px;
}}

.{name}-title {{
  font-family: 'Orbitron', 'Share Tech Mono', monospace;
  font-size: 1.2rem;
  color: var(--{name}-accent);
  letter-spacing: 2px;
  text-transform: uppercase;
}}

.{name}-main {{
  display: grid;
  gap: 16px;
}}
'''


# ──── Test Template ──────────────────────────────────────────────────────

_TEST_TEMPLATE = '''\
"""
Tests for {display_name} Scene
{test_header_line}

Version: v1.0.0 [{today}]

Covers:
    - Scene class instantiation
    - HTTP routes return 200
    - Socket.IO handlers respond
"""
from __future__ import annotations

import pytest
from unittest.mock import patch


@pytest.fixture
def scene_app():
    """Create a test instance of {class_name}."""
    with patch("engine.port_registry.get_port", return_value={port}):
        from content.scenes.{name}.{name}_scene import {class_name}
        scene = {class_name}(port={port})
        scene.app.config["TESTING"] = True
        yield scene


@pytest.fixture
def client(scene_app):
    """Flask test client for {class_name}."""
    return scene_app.app.test_client()


class Test{class_name}Routes:
    """HTTP route tests for {display_name}."""

    def test_index_returns_200(self, client) -> None:
        resp = client.get("/")
        assert resp.status_code == 200

    def test_health_returns_200(self, client) -> None:
        resp = client.get("/health")
        assert resp.status_code == 200

    def test_scene_state_api(self, client) -> None:
        resp = client.get("/api/scene/state")
        assert resp.status_code == 200
        data = resp.get_json()
        assert data["scene_id"] == "{name}"
'''


# ──── Scaffolding Function ───────────────────────────────────────────────


def _hex_to_rgb(hex_color: str) -> str:
    """Convert hex color to space-separated RGB string.

    Args:
        hex_color: CSS hex color (e.g. ``"#06b6d4"``).

    Returns:
        Space-separated RGB string (e.g. ``"6 182 212"``).
    """
    hex_color = hex_color.lstrip("#")
    if len(hex_color) == 3:
        hex_color = "".join(c * 2 for c in hex_color)
    try:
        r, g, b = int(hex_color[0:2], 16), int(hex_color[2:4], 16), int(hex_color[4:6], 16)
        return f"{r} {g} {b}"
    except (ValueError, IndexError):
        return "6 182 212"


def _hex_to_rgb_csv(hex_color: str) -> str:
    """Convert hex color to comma-separated RGB for CSS rgba().

    Args:
        hex_color: CSS hex color (e.g. ``"#06b6d4"``).

    Returns:
        Comma-separated RGB string (e.g. ``"6, 182, 212"``).
    """
    return _hex_to_rgb(hex_color).replace(" ", ", ")


def create_scene(
    name: str,
    display_name: Optional[str] = None,
    port: int = 5590,
    accent: str = "#00e5ff",
    description: str = "",
    template: str = "basic",
    generate_test: bool = True,
    auto_register: bool = True,
) -> Path:
    """Scaffold a new scene directory with production-quality boilerplate.

    Generates: ``{name}_scene.py``, ``{name}.html``, ``{name}.js``,
    ``{name}.css``, ``test_{name}.py``, and ``__init__.py``.  Optionally
    registers the scene in ``control_plane_registry.py`` and
    ``config/launcher.yaml``.

    Args:
        name: Machine name (snake_case, e.g. ``"my_scene"``).
        display_name: Human-readable name. Defaults to title-cased *name*.
        port: Default port assignment.
        accent: CSS accent colour hex.
        description: Short scene description.
        template: Template variant (currently only ``"basic"``).
        generate_test: If True, also create ``tests/test_{name}.py``.
        auto_register: If True, add scene to control_plane_registry and
                       launcher.yaml.

    Returns:
        Path to the created scene directory.

    Raises:
        FileExistsError: If the scene directory already exists.
    """
    scene_dir = SCENES_DIR / name
    if scene_dir.exists():
        raise FileExistsError(f"Scene directory already exists: {scene_dir}")

    display_name = display_name or name.replace("_", " ").title()
    class_name = "".join(w.capitalize() for w in name.split("_")) + "Scene"
    app_var = class_name.replace("Scene", "App")
    today = date.today().isoformat()
    accent_rgb = _hex_to_rgb(accent)
    accent_rgb_csv = _hex_to_rgb_csv(accent)

    header_line = "=" * (len(display_name) + len(" — CosySim Scene"))
    js_header_line = "=" * (len(name) + len(".js — ") + len(display_name) + len(" Scene Controller"))
    css_header_line = "=" * (len(name) + len(".css — ") + len(display_name) + len(" Scene Styles"))
    test_header_line = "=" * (len("Tests for ") + len(display_name) + len(" Scene"))

    ctx = {
        "name": name,
        "display_name": display_name,
        "class_name": class_name,
        "app_var": app_var,
        "port": port,
        "accent": accent,
        "accent_rgb": accent_rgb,
        "accent_rgb_csv": accent_rgb_csv,
        "description": description or f"{display_name} scene",
        "header_line": header_line,
        "js_header_line": js_header_line,
        "css_header_line": css_header_line,
        "test_header_line": test_header_line,
        "today": today,
    }

    # ── Create directory structure ────────────────────────────────────
    (scene_dir / "templates").mkdir(parents=True, exist_ok=True)
    (scene_dir / "static").mkdir(parents=True, exist_ok=True)

    # ── Write scene files ────────────────────────────────────────────
    (scene_dir / "__init__.py").write_text(
        f'"""CosySim scene: {display_name}."""\n', encoding="utf-8"
    )
    (scene_dir / f"{name}_scene.py").write_text(
        _SCENE_PY_TEMPLATE.format(**ctx), encoding="utf-8"
    )
    (scene_dir / "templates" / f"{name}.html").write_text(
        _HTML_TEMPLATE.format(**ctx), encoding="utf-8"
    )
    (scene_dir / "static" / f"{name}.js").write_text(
        _JS_TEMPLATE.format(**ctx), encoding="utf-8"
    )
    (scene_dir / "static" / f"{name}.css").write_text(
        _CSS_TEMPLATE.format(**ctx), encoding="utf-8"
    )

    # ── Write test file ──────────────────────────────────────────────
    if generate_test:
        test_dir = PROJECT_ROOT / "tests"
        test_file = test_dir / f"test_{name}.py"
        if not test_file.exists():
            test_file.write_text(_TEST_TEMPLATE.format(**ctx), encoding="utf-8")
            logger.info("Generated test file: %s", test_file)

    # ── Auto-register in control plane ───────────────────────────────
    if auto_register:
        _register_scene(name, display_name, class_name, port, accent)

    logger.info("Scaffolded scene '%s' at %s", name, scene_dir)
    return scene_dir


# ──── Auto-Registration ──────────────────────────────────────────────────

# v1.52.0 [2026-03-22] — Register new scenes in control_plane_registry + launcher.yaml
# CONNECTS: control_plane_registry.py, config/launcher.yaml
# CALLED BY: create_scene() when auto_register=True


def _register_scene(
    name: str,
    display_name: str,
    class_name: str,
    port: int,
    accent: str,
) -> None:
    """Register a scene in control_plane_registry.py and launcher.yaml.

    Appends the scene to ``SCENE_DEFS`` in the registry module and adds
    an entry to ``config/launcher.yaml`` under ``scenes:``.

    Args:
        name: Scene machine name (snake_case).
        display_name: Scene display name.
        class_name: Scene class name (PascalCase + "Scene").
        port: Default port.
        accent: CSS accent colour hex.
    """
    # ── Register in control_plane_registry.py ────────────────────────
    registry_path = PROJECT_ROOT / "engine" / "control_plane_registry.py"
    if registry_path.exists():
        content = registry_path.read_text(encoding="utf-8")
        # Check if already registered
        if f'"{name}"' in content and "SCENE_DEFS" in content:
            logger.debug("Scene '%s' already in control_plane_registry", name)
        else:
            # Find the closing brace of SCENE_DEFS and insert before it
            cls_path = f"content.scenes.{name}.{name}_scene.{class_name}"
            entry = (
                f'    # v1.52.0 — Auto-registered by Creation Kit\n'
                f'    "{name}": {{\n'
                f'        "type": "flask",\n'
                f'        "cls": "{cls_path}",\n'
                f'        "label": "{display_name}",\n'
                f'        "auto_start": False,\n'
                f'        "pillar": "game",\n'
                f'    }},\n'
            )
            # Insert before the closing "}" of SCENE_DEFS
            # Find the pattern: last entry in SCENE_DEFS followed by "}"
            marker = "}\n\n# ──── Derived ID Tuples"
            if marker in content:
                content = content.replace(marker, entry + "}\n\n# ──── Derived ID Tuples")
                registry_path.write_text(content, encoding="utf-8")
                logger.info("Registered '%s' in control_plane_registry.py", name)
            else:
                logger.warning("Could not find SCENE_DEFS closing marker in control_plane_registry.py")

    # ── Register in launcher.yaml ────────────────────────────────────
    launcher_yaml = PROJECT_ROOT / "config" / "launcher.yaml"
    if launcher_yaml.exists():
        yaml_content = launcher_yaml.read_text(encoding="utf-8")
        if f"  {name}:" not in yaml_content:
            # Find the "scenes:" section and append
            scenes_entry = f"  {name}:\n    auto_start: false\n"
            if "scenes:" in yaml_content:
                # Insert after "scenes:" line
                yaml_content = yaml_content.replace(
                    "scenes:\n", f"scenes:\n{scenes_entry}", 1
                )
                launcher_yaml.write_text(yaml_content, encoding="utf-8")
                logger.info("Registered '%s' in launcher.yaml", name)
        else:
            logger.debug("Scene '%s' already in launcher.yaml", name)

    # ── Register port ────────────────────────────────────────────────
    port_registry = PROJECT_ROOT / "engine" / "port_registry.py"
    if port_registry.exists():
        port_content = port_registry.read_text(encoding="utf-8")
        if f'"{name}"' not in port_content:
            # Find _DEFAULT_PORTS dict and add entry
            marker = "}\n\n# Aliases"
            if "_DEFAULT_PORTS" in port_content and marker in port_content:
                port_entry = f'    "{name}": {port},\n'
                port_content = port_content.replace(marker, port_entry + marker)
                port_registry.write_text(port_content, encoding="utf-8")
                logger.info("Registered port %d for '%s' in port_registry.py", port, name)
