"""Per-NPC location, activity, and last-action state.

Provides a thread-safe registry of NPC runtime state, bridging the
WorldSim database with the MCP framework.
"""
from __future__ import annotations

import logging
import threading
import time
from dataclasses import dataclass, field
from typing import Dict, List, Optional

logger = logging.getLogger(__name__)

# ──── NPC State Dataclass ────


@dataclass
class NPCState:
    """Runtime state for a single NPC.

    Attributes:
        character_id: Unique NPC identifier (matches WorldSim / CharacterRegistry).
        location: Current in-world location string.
        activity: Short description of what the NPC is doing right now.
        last_action: The most recent action text generated by NPCScheduler.
        last_action_time: Unix timestamp of when last_action was recorded.
        mood: Emotional tone (e.g. "neutral", "happy", "tense").
        is_busy: True while the NPC has an active scheduled activity.
    """

    character_id: str
    location: str = "unknown"
    activity: str = "idle"
    last_action: str = ""
    last_action_time: float = field(default_factory=time.time)
    mood: str = "neutral"
    is_busy: bool = False

    def to_dict(self) -> Dict:
        """Serializable snapshot of this state."""
        return {
            "character_id": self.character_id,
            "location": self.location,
            "activity": self.activity,
            "last_action": self.last_action,
            "last_action_time": self.last_action_time,
            "mood": self.mood,
            "is_busy": self.is_busy,
        }


# ──── Registry ────


class NPCStateRegistry:
    """Thread-safe registry of all known NPC runtime states.

    Use :func:`get_npc_state_registry` to obtain the singleton instance.
    """

    def __init__(self) -> None:
        self._states: Dict[str, NPCState] = {}
        self._lock = threading.Lock()

    # ──── Read ────

    def get(self, character_id: str) -> Optional[NPCState]:
        """Return the state for *character_id*, or ``None`` if unknown.

        Args:
            character_id: The NPC to look up.

        Returns:
            The :class:`NPCState` if registered, else ``None``.
        """
        with self._lock:
            return self._states.get(character_id)

    def get_all(self) -> List[NPCState]:
        """Return all registered NPC states.

        Returns:
            List of :class:`NPCState` objects (unordered).
        """
        with self._lock:
            return list(self._states.values())

    def list_all(self) -> List[NPCState]:
        """Alias for :meth:`get_all` — returns all registered NPC states."""
        return self.get_all()

    def list_busy(self) -> List[NPCState]:
        """Return only NPCs currently marked as busy.

        Returns:
            Filtered list of :class:`NPCState` where ``is_busy`` is ``True``.
        """
        with self._lock:
            return [s for s in self._states.values() if s.is_busy]

    def to_dict(self) -> Dict[str, dict]:
        """Return a fully serializable snapshot of the entire registry.

        Returns:
            Mapping of character_id → state dict.
        """
        with self._lock:
            return {cid: state.to_dict() for cid, state in self._states.items()}

    # ──── Write ────

    def update(self, character_id: str, **kwargs) -> NPCState:
        """Create or update the state for *character_id*.

        Any keyword argument that matches an :class:`NPCState` field will be
        applied.  After the update, a ``npc_state_changed`` event is emitted
        on the MCPFramework event bus (best-effort; errors are logged but not
        re-raised).

        Args:
            character_id: The NPC to update.
            **kwargs: Field overrides (``location``, ``activity``, etc.).

        Returns:
            The updated :class:`NPCState`.
        """
        with self._lock:
            state = self._states.get(character_id)
            if state is None:
                state = NPCState(character_id=character_id)
                self._states[character_id] = state
            for key, value in kwargs.items():
                if hasattr(state, key):
                    setattr(state, key, value)
                else:
                    logger.warning("NPCStateRegistry.update: unknown field %r", key)
            snapshot = state.to_dict()

        self._fire_event(character_id, snapshot)
        return state

    # ──── Internal ────

    def _fire_event(self, character_id: str, snapshot: dict) -> None:
        """Emit npc_state_changed on the MCPFramework (best-effort)."""
        try:
            from engine.mcp import get_framework
            fw = get_framework()
            fw.emit("npc_state_changed", {
                "character_id": character_id,
                "state": snapshot,
            })
        except Exception as exc:
            logger.debug("NPCStateRegistry: could not fire event: %s", exc)


# ──── Singleton ────

_registry: Optional[NPCStateRegistry] = None
_registry_lock = threading.Lock()


def get_npc_state_registry() -> NPCStateRegistry:
    """Return the singleton :class:`NPCStateRegistry`.

    Returns:
        The global registry instance.
    """
    global _registry
    if _registry is None:
        with _registry_lock:
            if _registry is None:
                _registry = NPCStateRegistry()
    return _registry


def get_npc_state() -> NPCStateRegistry:
    """Alias for :func:`get_npc_state_registry`.

    Returns:
        The global registry instance.
    """
    return get_npc_state_registry()
