"""Asset Library — SQLite-backed catalogue for all generated assets.

Every asset generated by the Asset Studio (images, portraits, voice clips,
video, items, SVG, audio) is registered here with full metadata. The
library supports search, filter, bulk delete, and Nexus export.

Schema (assets table):
    id          TEXT PRIMARY KEY  — UUID4 hex
    asset_type  TEXT              — image|portrait|voice|video|item|svg|audio
    title       TEXT              — human-readable name
    scene       TEXT              — scene slug this was generated for (empty = global)
    character_id TEXT             — associated character (empty = none)
    mood        TEXT              — mood/style tag
    preset_id   TEXT              — preset used during generation
    prompt      TEXT              — positive prompt used
    negative    TEXT              — negative prompt used
    url         TEXT              — path or URL to the asset file
    metadata    TEXT              — JSON-encoded extra metadata
    nexus_key   TEXT              — Nexus cache key if cached
    created_at  TEXT              — ISO-8601 UTC timestamp
    duration_ms INTEGER           — generation wall-clock milliseconds
    cached      INTEGER           — 1 if served from cache, 0 otherwise
    favorite    INTEGER           — 1 if starred by user
"""
from __future__ import annotations

import json
import logging
import sqlite3
import threading
import uuid
from datetime import datetime, timezone
from pathlib import Path
from typing import Any, Dict, List, Optional

from engine.config import get_config

logger = logging.getLogger(__name__)


class AssetLibrary:
    """SQLite-backed asset catalogue for the Asset Studio.

    Thread-safe via a per-instance lock.  The database is created at the path
    configured by ``asset_studio.library_db`` (default: ``data/asset_library.db``).
    """

    def __init__(self, db_path: Optional[str] = None) -> None:
        """Initialise library, creating the DB and schema if needed.

        Args:
            db_path: Explicit path override for the SQLite database file.
        """
        if db_path is None:
            cfg = get_config()
            db_path = cfg.get("asset_studio.library_db", "data/asset_library.db")

        self._db_path = Path(db_path)
        self._db_path.parent.mkdir(parents=True, exist_ok=True)
        self._lock = threading.Lock()
        self._ensure_schema()

    # ── Schema ────────────────────────────────────────────────────────────────

    def _ensure_schema(self) -> None:
        """Create tables if they do not already exist."""
        with self._connect() as conn:
            conn.execute("""
                CREATE TABLE IF NOT EXISTS assets (
                    id          TEXT PRIMARY KEY,
                    asset_type  TEXT NOT NULL,
                    title       TEXT NOT NULL DEFAULT '',
                    scene       TEXT NOT NULL DEFAULT '',
                    character_id TEXT NOT NULL DEFAULT '',
                    mood        TEXT NOT NULL DEFAULT 'neutral',
                    preset_id   TEXT NOT NULL DEFAULT '',
                    prompt      TEXT NOT NULL DEFAULT '',
                    negative    TEXT NOT NULL DEFAULT '',
                    url         TEXT NOT NULL DEFAULT '',
                    metadata    TEXT NOT NULL DEFAULT '{}',
                    nexus_key   TEXT NOT NULL DEFAULT '',
                    created_at  TEXT NOT NULL,
                    duration_ms INTEGER NOT NULL DEFAULT 0,
                    cached      INTEGER NOT NULL DEFAULT 0,
                    favorite    INTEGER NOT NULL DEFAULT 0
                )
            """)
            conn.execute(
                "CREATE INDEX IF NOT EXISTS idx_assets_type ON assets (asset_type)"
            )
            conn.execute(
                "CREATE INDEX IF NOT EXISTS idx_assets_scene ON assets (scene)"
            )
            conn.execute(
                "CREATE INDEX IF NOT EXISTS idx_assets_char ON assets (character_id)"
            )
            conn.execute(
                "CREATE INDEX IF NOT EXISTS idx_assets_created ON assets (created_at DESC)"
            )

    def _connect(self) -> sqlite3.Connection:
        """Open a connection with row_factory set."""
        conn = sqlite3.connect(str(self._db_path), check_same_thread=False)
        conn.row_factory = sqlite3.Row
        return conn

    # ── Write ─────────────────────────────────────────────────────────────────

    def register(
        self,
        asset_type: str,
        url: str,
        title: str = "",
        scene: str = "",
        character_id: str = "",
        mood: str = "neutral",
        preset_id: str = "",
        prompt: str = "",
        negative: str = "",
        metadata: Optional[Dict[str, Any]] = None,
        nexus_key: str = "",
        duration_ms: int = 0,
        cached: bool = False,
    ) -> str:
        """Register a new asset and return its generated ID.

        Args:
            asset_type: One of image|portrait|voice|video|item|svg|audio.
            url: Filesystem path or HTTP URL to the asset.
            title: Human-readable title.
            scene: Scene slug (empty = global).
            character_id: Associated character (empty = none).
            mood: Mood/style tag.
            preset_id: Preset used during generation.
            prompt: Positive prompt used.
            negative: Negative prompt.
            metadata: Extra key/value metadata.
            nexus_key: Nexus cache key if persisted.
            duration_ms: Generation wall-clock milliseconds.
            cached: Whether result was served from cache.

        Returns:
            The UUID4-hex asset ID.
        """
        asset_id = uuid.uuid4().hex
        now = datetime.now(timezone.utc).isoformat()
        meta_json = json.dumps(metadata or {})

        if not title:
            title = f"{asset_type}/{scene or 'global'}/{mood}"

        with self._lock:
            with self._connect() as conn:
                conn.execute(
                    """INSERT INTO assets
                       (id, asset_type, title, scene, character_id, mood,
                        preset_id, prompt, negative, url, metadata,
                        nexus_key, created_at, duration_ms, cached, favorite)
                       VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,0)""",
                    (
                        asset_id, asset_type, title, scene, character_id,
                        mood, preset_id, prompt, negative, url, meta_json,
                        nexus_key, now, duration_ms, int(cached),
                    ),
                )

        logger.debug("Registered %s asset %s (%s)", asset_type, asset_id[:8], title)
        return asset_id

    def delete(self, asset_id: str) -> bool:
        """Delete an asset by ID.

        Args:
            asset_id: UUID4-hex asset ID.

        Returns:
            ``True`` if a row was deleted, ``False`` if not found.
        """
        with self._lock:
            with self._connect() as conn:
                cursor = conn.execute(
                    "DELETE FROM assets WHERE id = ?", (asset_id,)
                )
                return cursor.rowcount > 0

    def toggle_favorite(self, asset_id: str) -> bool:
        """Toggle the favorite flag for an asset.

        Args:
            asset_id: UUID4-hex asset ID.

        Returns:
            The new favorite state (``True`` = favorited).
        """
        with self._lock:
            with self._connect() as conn:
                row = conn.execute(
                    "SELECT favorite FROM assets WHERE id = ?", (asset_id,)
                ).fetchone()
                if row is None:
                    return False
                new_val = 1 - row["favorite"]
                conn.execute(
                    "UPDATE assets SET favorite = ? WHERE id = ?",
                    (new_val, asset_id),
                )
                return bool(new_val)

    # ── Query ─────────────────────────────────────────────────────────────────

    def list_assets(
        self,
        asset_type: Optional[str] = None,
        scene: Optional[str] = None,
        character_id: Optional[str] = None,
        favorites_only: bool = False,
        limit: int = 100,
        offset: int = 0,
        search: Optional[str] = None,
    ) -> List[Dict[str, Any]]:
        """Return a filtered, paginated list of assets.

        Args:
            asset_type: Filter by type (None = all types).
            scene: Filter by scene slug (None = all scenes).
            character_id: Filter by character (None = all).
            favorites_only: Return only starred assets.
            limit: Max rows to return.
            offset: Rows to skip.
            search: Substring filter on title + prompt.

        Returns:
            List of asset dicts (all columns, metadata decoded to dict).
        """
        clauses: List[str] = []
        params: List[Any] = []

        if asset_type:
            clauses.append("asset_type = ?")
            params.append(asset_type)
        if scene:
            clauses.append("scene = ?")
            params.append(scene)
        if character_id:
            clauses.append("character_id = ?")
            params.append(character_id)
        if favorites_only:
            clauses.append("favorite = 1")
        if search:
            clauses.append("(title LIKE ? OR prompt LIKE ?)")
            params.extend([f"%{search}%", f"%{search}%"])

        where = f"WHERE {' AND '.join(clauses)}" if clauses else ""
        params.extend([limit, offset])

        with self._connect() as conn:
            rows = conn.execute(
                f"SELECT * FROM assets {where} "
                f"ORDER BY created_at DESC LIMIT ? OFFSET ?",
                params,
            ).fetchall()

        return [self._row_to_dict(r) for r in rows]

    def get_asset(self, asset_id: str) -> Optional[Dict[str, Any]]:
        """Return a single asset by ID or ``None`` if not found."""
        with self._connect() as conn:
            row = conn.execute(
                "SELECT * FROM assets WHERE id = ?", (asset_id,)
            ).fetchone()
        return self._row_to_dict(row) if row else None

    def count(
        self,
        asset_type: Optional[str] = None,
        scene: Optional[str] = None,
    ) -> int:
        """Return the count of assets matching optional filters."""
        clauses, params = [], []
        if asset_type:
            clauses.append("asset_type = ?")
            params.append(asset_type)
        if scene:
            clauses.append("scene = ?")
            params.append(scene)
        where = f"WHERE {' AND '.join(clauses)}" if clauses else ""
        with self._connect() as conn:
            return conn.execute(
                f"SELECT COUNT(*) FROM assets {where}", params
            ).fetchone()[0]

    def stats(self) -> Dict[str, Any]:
        """Return per-type counts and total."""
        with self._connect() as conn:
            rows = conn.execute(
                "SELECT asset_type, COUNT(*) as cnt FROM assets GROUP BY asset_type"
            ).fetchall()
            total = conn.execute("SELECT COUNT(*) FROM assets").fetchone()[0]
        by_type = {r["asset_type"]: r["cnt"] for r in rows}
        return {"total": total, "by_type": by_type}

    # ── Helpers ───────────────────────────────────────────────────────────────

    @staticmethod
    def _row_to_dict(row: sqlite3.Row) -> Dict[str, Any]:
        """Convert a sqlite3.Row to a plain dict, decoding metadata JSON."""
        d = dict(row)
        try:
            d["metadata"] = json.loads(d.get("metadata", "{}") or "{}")
        except (json.JSONDecodeError, TypeError):
            d["metadata"] = {}
        d["cached"] = bool(d.get("cached", 0))
        d["favorite"] = bool(d.get("favorite", 0))
        return d


# ── Singleton ─────────────────────────────────────────────────────────────────

_library_instance: Optional[AssetLibrary] = None
_library_lock = threading.Lock()


def get_asset_library() -> AssetLibrary:
    """Return the process-wide :class:`AssetLibrary` singleton.

    Thread-safe; creates the instance on first call.

    Returns:
        The singleton :class:`AssetLibrary`.
    """
    global _library_instance
    if _library_instance is None:
        with _library_lock:
            if _library_instance is None:
                _library_instance = AssetLibrary()
    return _library_instance
