"""ARGUS API documentation generator — auto-generates API reference markdown.

Reads from:
    - ``data/argus/registry.json`` — endpoint registry
    - ``scripts/argus/config.py`` — baselines
    - Captured crawl results (passed in)

Writes:
    - ``docs/NLM_API_REFERENCE.md``
    - ``docs/GEMINI_API_REFERENCE.md``
    - ``docs/AISTUDIO_API_REFERENCE.md``
"""
from __future__ import annotations

import json
import logging
from datetime import datetime, timezone
from pathlib import Path
from typing import Any, Dict, List, Optional

from scripts.argus.config import (
    AISTUDIO_METHODS,
    GEMINI_RPCIDS,
    NLM_RPCIDS,
)
from scripts.argus.discovery.endpoint_registry import get_registry

logger = logging.getLogger(__name__)

DOCS_DIR = Path("docs")
_NOW = datetime.now(timezone.utc).strftime("%Y-%m-%d")


class ApiDocGenerator:
    """Generates Markdown API reference files from ARGUS discoveries."""

    def generate_nlm_reference(self) -> str:
        """Generate ``docs/NLM_API_REFERENCE.md`` content."""
        registry = get_registry()
        stats = registry.get_stats()
        reg_data = registry.get_full_data()

        lines: List[str] = [
            "# NotebookLM API Reference",
            "",
            f"> Auto-generated by ARGUS on {_NOW}",
            f"> Coverage: {stats['nlm_rpcids_seen']}/{stats['nlm_rpcids_total']} rpcids observed",
            "",
            "## Protocol",
            "",
            "**Endpoint:** `https://notebooklm.google.com/_/LabsTailwindUi/data/batchexecute`",
            "",
            "**Format:** `f.req=[[['rpcid','json_payload',null,'generic']]]`",
            "",
            "**Auth:** Session cookies (`__Secure-1PSID`, `__Secure-1PAPISID`)",
            "",
            "**Response:** `)]}'\n` prefix + `wrb.fr` JSON frames",
            "",
            "---",
            "",
            "## RPC Methods",
            "",
        ]

        for rpcid, name in sorted(NLM_RPCIDS.items(), key=lambda x: x[1]):
            entry = reg_data["nlm_rpcids"].get(rpcid, {})
            seen_count = entry.get("seen", 0)
            last_seen = entry.get("last", "never")
            status = "✅" if seen_count > 0 else "⚠️ not yet observed"

            lines += [
                f"### `{rpcid}` — {name}",
                "",
                f"- **Status:** {status}",
                f"- **Times observed:** {seen_count}",
                f"- **Last seen:** {last_seen}",
                "",
            ]

        # New discoveries section
        new_nlm = [
            (rpcid, d) for rpcid, d in reg_data["nlm_rpcids"].items()
            if rpcid not in NLM_RPCIDS and d.get("seen", 0) > 0
        ]
        if new_nlm:
            lines += [
                "---",
                "",
                "## 🆕 New Discoveries (not in baseline)",
                "",
            ]
            for rpcid, d in sorted(new_nlm):
                lines += [
                    f"### `{rpcid}`",
                    "",
                    f"- **First seen:** {d.get('first', '?')}",
                    f"- **Times seen:** {d.get('seen', 1)}",
                    "",
                ]

        lines += [
            "---",
            "",
            "## Feature Flags",
            "",
            "Feature flags are fetched via rpcid `ozz5Z` (GetFeatureFlags).",
            "See `data/argus/feature_flags.json` for the probed flag ID map.",
            "",
        ]

        return "\n".join(lines)

    def generate_gemini_reference(self) -> str:
        """Generate ``docs/GEMINI_API_REFERENCE.md`` content."""
        registry = get_registry()
        stats = registry.get_stats()
        reg_data = registry.get_full_data()

        lines: List[str] = [
            "# Gemini API Reference (Internal)",
            "",
            f"> Auto-generated by ARGUS on {_NOW}",
            f"> Coverage: {stats['gemini_rpcids_seen']}/{stats['gemini_rpcids_total']} rpcids observed",
            "",
            "## Protocol",
            "",
            "**Endpoint:** `https://gemini.google.com/_/BardFrontendService/data/batchexecute`",
            "",
            "**Format:** Same as NLM batchexecute",
            "",
            "**Special:** `NXpLKc` bridges to NLM ListLinkedNotebooks",
            "",
            "---",
            "",
            "## RPC Methods",
            "",
        ]

        for rpcid, name in sorted(GEMINI_RPCIDS.items(), key=lambda x: x[1]):
            entry = reg_data["gemini_rpcids"].get(rpcid, {})
            seen_count = entry.get("seen", 0)
            last_seen = entry.get("last", "never")
            status = "✅" if seen_count > 0 else "⚠️"

            lines += [
                f"### `{rpcid}` — {name}",
                "",
                f"- **Status:** {status}",
                f"- **Times observed:** {seen_count}",
                f"- **Last seen:** {last_seen}",
                "",
            ]

        return "\n".join(lines)

    def generate_aistudio_reference(self) -> str:
        """Generate ``docs/AISTUDIO_API_REFERENCE.md`` content."""
        registry = get_registry()
        stats = registry.get_stats()
        reg_data = registry.get_full_data()

        lines: List[str] = [
            "# AI Studio (MakerSuite) API Reference",
            "",
            f"> Auto-generated by ARGUS on {_NOW}",
            f"> Coverage: {stats['aistudio_methods_seen']}/{stats['aistudio_methods_total']} methods observed",
            "",
            "## Protocol",
            "",
            "**Endpoint:** `https://alkalimakersuite-pa.clients6.google.com/$rpc/google.internal.alkali.applications.makersuite.v1.MakerSuiteService/{Method}`",
            "",
            "**Auth:** `Authorization: SAPISIDHASH <ts>_<sha1>` + session cookies",
            "",
            "**SAPISIDHASH:** `sha1('{ts} {SAPISID} https://aistudio.google.com')`",
            "",
            "**Format:** gRPC-web with binary proto encoding OR JSON mode",
            "",
            "---",
            "",
            "## Methods",
            "",
        ]

        # Group methods by prefix
        method_groups: Dict[str, List[str]] = {}
        for method in sorted(AISTUDIO_METHODS):
            prefix = _method_prefix(method)
            method_groups.setdefault(prefix, []).append(method)

        for prefix, methods in sorted(method_groups.items()):
            lines += [f"### {prefix} Operations", ""]
            for method in methods:
                entry = reg_data["aistudio_methods"].get(method, {})
                seen_count = entry.get("seen", 0)
                status = "✅" if seen_count > 0 else "⚠️"
                lines += [
                    f"#### `{method}` {status}",
                    "",
                    f"- **Times observed:** {seen_count}",
                    f"- **Last seen:** {entry.get('last', 'never')}",
                    "",
                ]

        return "\n".join(lines)

    def write_all(self) -> List[Path]:
        """Write all API reference docs to docs/."""
        DOCS_DIR.mkdir(exist_ok=True)
        written: List[Path] = []

        pairs = [
            (DOCS_DIR / "NLM_API_REFERENCE.md", self.generate_nlm_reference()),
            (DOCS_DIR / "GEMINI_API_REFERENCE.md", self.generate_gemini_reference()),
            (DOCS_DIR / "AISTUDIO_API_REFERENCE.md", self.generate_aistudio_reference()),
        ]
        for path, content in pairs:
            path.write_text(content, encoding="utf-8")
            written.append(path)
            logger.info("ApiDocGenerator: wrote %s (%d chars)", path, len(content))

        return written


class DiffReporter:
    """Compares current registry vs previous scan and produces a diff report."""

    def __init__(self, current: Dict[str, Any], previous: Optional[Dict[str, Any]] = None) -> None:
        self._current = current
        self._previous = previous or {}

    def generate_report(self) -> str:
        """Generate a Markdown diff report."""
        lines = [
            "# ARGUS Scan Diff Report",
            "",
            f"> Generated: {_NOW}",
            "",
        ]

        # New NLM rpcids
        curr_nlm = set(self._current.get("nlm_rpcids", {}).keys())
        prev_nlm = set(self._previous.get("nlm_rpcids", {}).keys())
        new_nlm = curr_nlm - prev_nlm
        if new_nlm:
            lines += ["## 🆕 New NLM rpcids", ""]
            for r in sorted(new_nlm):
                lines.append(f"- `{r}`")
            lines.append("")

        # New Gemini rpcids
        curr_gem = set(self._current.get("gemini_rpcids", {}).keys())
        prev_gem = set(self._previous.get("gemini_rpcids", {}).keys())
        new_gem = curr_gem - prev_gem
        if new_gem:
            lines += ["## 🆕 New Gemini rpcids", ""]
            for r in sorted(new_gem):
                lines.append(f"- `{r}`")
            lines.append("")

        # New AI Studio methods
        curr_ais = set(self._current.get("aistudio_methods", {}).keys())
        prev_ais = set(self._previous.get("aistudio_methods", {}).keys())
        new_ais = curr_ais - prev_ais
        if new_ais:
            lines += ["## 🆕 New AI Studio methods", ""]
            for m in sorted(new_ais):
                lines.append(f"- `{m}`")
            lines.append("")

        if not new_nlm and not new_gem and not new_ais:
            lines.append("No new discoveries in this scan. Baseline unchanged.")

        return "\n".join(lines)


def _method_prefix(method: str) -> str:
    for prefix in ["List", "Get", "Create", "Update", "Delete", "Stream",
                   "Generate", "Count", "Batch", "Import", "Export", "Tune"]:
        if method.startswith(prefix):
            return prefix
    return "Other"
